# -*- coding: utf-8 -*-
"""Shared numeric defaults for RaisedFloor runtime modules."""

# Revit / geometry base conversions
MM_PER_FOOT = 304.8
GEOM_TOL = 1e-6
CLIPPER_SCALE = 1000.0

# Grid drawing
DEFAULT_STRINGER_CLEARANCE_MM = 30.0
MIN_SEGMENT_LENGTH_FT = 0.005  # ~1.5 mm
GRID_MARKER_ARM_FT = 0.45  # ~137 mm
GRID_MARKER_RING_HALF_FT = 0.18  # ~55 mm

# Placement defaults
DEFAULT_TILE_THICKNESS_MM = 40.0
DEFAULT_BOTTOM_STEP_MM = 1200.0
DEFAULT_MAX_STRINGER_LENGTH_MM = 4000.0
DEFAULT_SUPPORT_SPACING_MM = 1000.0
MOUNTING_GAP_MM = 5.0
MIN_VIABLE_TILE_WIDTH_MM = 100.0
VOID_HIDDEN_THRESHOLD_MM = 1.0
STRINGER_INTERSECTION_TOL_MM = 0.5

# Exact layout / optimization
ROUND_MM_DIGITS = 1
AREA_EQUAL_TOL_MM2 = 0.1
MIN_FRAGMENT_AREA_MM2 = 100.0
DEFAULT_MICRO_FRAGMENT_CUT_MM = 50.0
DEFAULT_UNACCEPTABLE_CUT_MM = 100.0
DEFAULT_UNWANTED_CUT_MM = 150.0
DEFAULT_ACCEPTABLE_CUT_MM = 200.0
DEFAULT_COARSE_SHIFT_STEP_MM = 50.0
DEFAULT_REFINE_SHIFT_STEP_MM = 10.0
DEFAULT_REFINE_RADIUS_MM = 60.0
DEFAULT_REFINE_TOP_N = 5
DEFAULT_TOP_N = 10
CUT_ROUND_MM = 10.0
SCAN_SAMPLES = 40
SCAN_EPS_MM = 0.05
SCAN_HIT_TOL_MM = 1e-4
BBOX_TOL_MM = 1.0
EDGE_TOL_MM = 0.05
